### ISSUE TITLE
Some examples #define POT_PIN, why?

### ISSUE THREAD

**Issue by biomurph** [Tympan/Tympan_Library#18]
Had to correct multiple examples that were defining the wrong POT_PIN number.
Is there a reason that some sketches have this #define? The other examples all use the library readPotentiomenter function call.

**Comment by chipaudette** [comment]
The only reason POT_PIN still exists in some sketches is that they've not yet been updated to the new approach (ie, using the Tympan class and its associated "readPotentiomenter()" method).

All sketches should be updated to use the Tympan class instead.  It's my fault that some were missed.

**Comment by biomurph** [comment]
Alright, cool. When I have time I will look in and see if there are still outstanding I can knock them out pretty quick.
