### ISSUE TITLE
RevE Review of Getting Started docs

### ISSUE THREAD

**Issue by chipaudette** [Tympan/Tympan_Library#36]
Prior to release of RevE, we need to update our Getting Started docs.  

There are several getting started docs.  Please review update all:

 

- [x]  The readme of the [main repo](https://github.com/Tympan/Tympan_Library/tree/master), which you see displayed automatically when you scroll down a little bit, has some quick getting-started info

- [x]  The main repo also has a [wiki](https://github.com/Tympan/Tympan_Library/wiki), though it doesn't say much except point to our other docs.  Please make sure the links work.
- [x]  The full Getting Started docs are [here](https://github.com/Tympan/Docs/wiki/Getting-Starting-with-Tympan)
- [x] Add documentation on using TympanRemote App
 

Here are the specific goals of this update:

  * The docs should be approachable and helpful
  * The docs should be applicable to both RevD and RevE
  * ~~The docs do need to be changed to point to the beta release of Teensyduino~~
    * ~~The beta is downloaded from [the forum](https://forum.pjrc.com/threads/67252-Teensyduino-1-54-Beta-9)~~
    * Otherwise, the Teensy people's [installation instructions](https://www.pjrc.com/teensy/td_download.html) can be followed, like usual
  * This update of the docs will not involve changing the photos, unless the photos are misleading
  * This update of the docs could involve updating the screenshots...please review the screenshots and recommend whether you think it is necessary

**Comment by hgeithner-creare** [comment]
I know we can no longer use [travis-ci.org](travis-ci.org) and have to use [travis-ci.com](travis-ci.com). I'm not sure how you want to go about updating the [Travis CI Integration](https://github.com/Tympan/Tympan_Library/wiki#travis-ci-integration) section.

![image](https://user-images.githubusercontent.com/85691451/126212694-d79c5915-b4d4-47e9-a1db-8274450b6271.png)

**Comment by chipaudette** [comment]
It's OK to leave the Travis stuff to someone else, like maybe @kxm-creare, if he's ever able to get back to this.

**Comment by hgeithner-creare** [comment]
I can update the Getting Started docs for the TympanRemote App once @kxm-creare releases a new version.

**Comment by hgeithner-creare** [comment]
I'm going to close this issue. Let me know if I need to make a separate issue on updating the Travis CI stuff.
