### ISSUE TITLE
Wrong pin on micro specified for AIC reset

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Library#40]
@chipaudette I believe the wrong Tympan pin is assigned to reset the AIC , not that it matters.  When the AIC boots up it will reset to default anyway.  

Here is the Rev-D board showing pin A8 is connected to nReset
<img src = "https://user-images.githubusercontent.com/42774675/124332490-90a46100-db5f-11eb-84b5-fa42768ef19d.png" height = 500/>

Teensy 3.6 diagram shows A8 is pin#22
![image](https://user-images.githubusercontent.com/42774675/124336264-52ad3a00-db6b-11eb-801f-59023eb2429e.png)

Reset pin defined as pin#21 on Teensy 3.6
https://github.com/Tympan/Tympan_Library/blob/c44b8c3d6fce48084498e54583e6e4b5d78af186/src/control_aic3206.h#L45

![image](https://user-images.githubusercontent.com/42774675/124336421-fe568a00-db6b-11eb-9a76-3aeb27fb29e4.png)

Digital write called to reset the AIC
![image](https://user-images.githubusercontent.com/42774675/124336395-e7b03300-db6b-11eb-8638-1a8db2c55046.png)

Looks like this was never got updated from  the Teensy 3.2<br>
![image](https://user-images.githubusercontent.com/42774675/124336541-686f2f00-db6c-11eb-8cf8-eabdf0b935e4.png)

**Comment by biomurph** [comment]
@eyuan-creare @chipaudette 
Eric you are looking at a reference to the ball array position. 
The pin number is A8 as you say, but that is only reference to the pin number of the BGA
Note in the schematic that I have listed the Teensy pin numbers in BLUE alongside the BGA pin numbers.
<img width="845" alt="Screen Shot 2021-07-05 at 12 20 56 PM" src="https://user-images.githubusercontent.com/6284057/124499360-d8a7cb80-dd8b-11eb-8c02-e18f684cf2dc.png">

**Comment by eyuan-creare** [comment]
@biomurph Thanks for taking a look and straightening me out.  That makes sense.  So is it okay that nReset is assigned to Pin21?

 #define AIC3206_DEFAULT_RESET_PIN 21

**Comment by biomurph** [comment]
The nRESET pin is connected to Teensy pin 35 on Rev D

**Comment by chipaudette** [comment]
In practice, the nReset gets set by the creation of the Tympan class.  I believe that this overwrites the nReset pin away from the default set by this #define and to whatever pin is specified in Tympan.h for whichever rev you are using.  So, in effect, this #define ends up getting ignored.

Since I created the whole Tympan.h way of handling the diff Tympan revs back for the release of RevD, I bet that #define value is what was used for RevA/RevC.  It's like you found a fossil

**Comment by chipaudette** [comment]
With your work on the AIC3216, we have to decide whether to fold it into Tympan.h as another variant of Tympan, or whether we create a whole new class.

Given that Tympan.h extends AIC3206, it seems like switching to 3212 breaks that underlying assumption.  We could abstract the interaction with the AIC, but that only makes sense if they offer similar functionality.  I'm not sure that they do.  I think that creating a new AIC3212 class (modeled on the 3206 class...or not) is probably the right path.
