### ISSUE TITLE
App: addCard_audioSource not displaying

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Library#58]
In [TrebleBoost_wComp_wEarpieces_wApp](https://github.com/Tympan/Tympan_Library/tree/main/examples/09-Earpieces), the first page does not show options for selecting audio source.

Here is the code as of b173ad9c67148aca65d93873728ac156479422ee
```
TR_Card* EarpieceMixer_F32_UI::addCard_audioSource(TR_Page *page_h) {
  if (page_h == NULL) return NULL;
  TR_Card *card_h = page_h->addCard("Audio Source");
  if (card_h == NULL) return NULL;
  String prefix = String(quadchar_start_char)+String(ID_char)+String("x");
  card_h->addButton(F("Digital Earpieces"),       prefix+"d", F("configPDMMic"),   12); //label, command, id, width
  card_h->addButton(F("Analog: PCB Mics"),        prefix+"w", F("configPCBMic"),   12); //label, command, id, width
  card_h->addButton(F("Analog: Mic Jack (Mic)"),  prefix+"W", F("configMicJack"),  12); //label, command, id, width
  card_h->addButton(F("Analog: Mic Jack (Line)"), prefix+"e", F("configLineJack"), 12); //label, command, id, width
  card_h->addButton(F("Analog: BT Audio"),        prefix+"E", F("configLineSE"),   12); //label, command, id, width
  return card_h;
}
```

![Screenshot_20210922-230841_Tympan Remote](https://user-images.githubusercontent.com/42774675/134449439-089ca94c-cd63-48e4-a846-ebfe29ff8f01.jpg)

**Comment by chipaudette** [comment]
Using release_candidate1, I was not able to recreate this problem.  I successfully get the menu that you were missing.

![image](https://user-images.githubusercontent.com/1806494/134559028-c40a4f97-5ef2-48ed-b289-51ca9fcee56f.png)

**Comment by hgeithner-creare** [comment]
I tried this example on main and successfully got the menu.

**Comment by eyuan-creare** [comment]
Closing this.  I believe the recent changes fixed this.  Thanks!
