### ISSUE TITLE
Capitalisation error with Linux build

### ISSUE THREAD

**Issue by noeldiviney** [Tympan/Tympan_Library#6]
Hi,

Firstly a big thank you for your great work with tympan. I am learning a lot from it, being new to Arduino.

Building under Linux using the Arduino ide V1.8.3 fails with the following error.
"/home/noel/Arduino/libraries/Tympan_Library/Tympan_Library.h:3:30: fatal error: BTNRH_WDRC_Types.h: No such file or directory"

The quick and dirty solution is to rename the header file in the Library to BTNRH_WDRC_Types.h

Best regards.
Noel Diviney

**Comment by chipaudette** [comment]
Good find!

I changed the filename capitalization, as you suggested.  Interestingly, the Windows GitHub client doesn't even see the capitalization change, so I couldn't commit the change.  I had to pull the file out of the repo, commit the removal, then put it back in the repo and re-commit it.  Weird.

Thanks again!

Chip
