### ISSUE TITLE
Case consistency for Linux

### ISSUE THREAD

**Issue by mathieulegoc** [Tympan/Tympan_Library#74]
Most files use `#include "AudioEffectDelay_F32.h"`, but `Tympan_Library.h` and `AudioEffectDelay_f32.cpp` use `#include "AudioEffectDelay_f32.h"`, causing the compilation to fail on Linux.

**Comment by chipaudette** [comment]
Good catch!  Will fix today.

**Comment by chipaudette** [comment]
As of commit 72deda3, I believe that this is now fixed.  I do not run linux, however, so I can't confirm.

Please update your Tympan_Library and let me know!

**Comment by mathieulegoc** [comment]
Thank you for the quick fix, all good now!

**Comment by chipaudette** [comment]
Fantastic!
